namespace: ${APP_NAME}-${ENV_NAME}
appName: ${APP_NAME}
replicas: ${POD_REPLICAS}
imageLocation: ${IMAGE_NAME}
registrySecretName: ${REGISTRY_SECRET_NAME}
containerPorts:
  - name: http
    port: 80
    targetPort: 3000
envVars:
  ORIGIN: https://${FULL_DOMAIN}
  IS_PREVIEW: ${IS_PREVIEW}
  PUBLIC_API_URL: ${PUBLIC_API_URL}
  PUBLIC_SENTRY_DSN: ${SENTRY_DSN}
  PUBLIC_SENTRY_RELEASE: ${SENTRY_RELEASE}
  PUBLIC_ENV_NAME: ${ENV_NAME}
  NODE_TLS_REJECT_UNAUTHORIZED: ${NODE_TLS_REJECT_UNAUTHORIZED}

secrets:
  - name: test-secrets
    type: Opaque
    data:
      SECRET_TEST_KEY: secret

clusterIssuerName: ${CLUSTER_ISSUER}
tlsSecretName: tls-${APP_NAME}-${ENV_NAME}
# ingress values are added below here during deploy pipeline
