namespace: ${APP_NAME}-${NAMESPACE_SUFFIX}
appName: ${APP_NAME}
replicas: ${POD_REPLICAS}
imageLocation: ${IMAGE_NAME}
registrySecretName: ${REGISTRY_SECRET_NAME}
containerPorts:
  - name: http
    port: 80
    targetPort: 3000
envVars:
  PUBLIC_TEST_KEY: public
  ORIGIN: https://${FULL_DOMAIN}

secrets:
  - name: test-secrets
    type: Opaque
    data:
      SECRET_TEST_KEY: secret

clusterIssuerName: ${CLUSTER_ISSUER}
domainName: ${FULL_DOMAIN}
tlsSecretName: tls-${APP_NAME}-${NAMESPACE_SUFFIX}
ingressPaths:
  - path: /
    type: Prefix
    servicePort: 80
